services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - production-test
  nest:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: tfd-nest
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
      - ./backend/.env:/app/.env
      - ./backend/upload:/app/upload
    networks:
      - production-test
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: tfd-nest-nginx
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 8080:8080
    networks:
      - production-test
  db:
    image: postgres:12
    container_name: tfd-nest-db
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql
    networks:
      - production-test
  redis:
    image: redis:5
    container_name: tfd-redis
    ports:
      - 6379:6379
    networks:
      - production-test
volumes:
  postgresdata:

networks:
  production-test:
    name: production-test
    external: true
