name: Deploy to VM
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 213.199.45.4
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd ~/apps/devops/devops-deploy
            git pull
            git submodule init
            git submodule update
            nvm install 16
            nvm use 16
            docker compose down
            docker compose build
            docker compose up -d