name: DevOps-Assignment
on:
  push:
    branches:
      - main
  pull_request:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Remote to Contabo Server by SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 213.199.45.4
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd ~/apps/devops/devops-deploy
            git pull
            git submodule init
            git submodule update
            nvm install 16
            nvm use 16
            docker compose down
            docker compose build
            docker compose up -d
