name: DevOps-Assignment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.02
    steps:
      - name: Remote to Contabo Server by SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 213.199.45.4
          username: root
          key: ${{ secrets.CONTABO_TOKEN }}
          port: 22
          script: |
            cd apps/devops/devops-deploy
            git pull
            git submodule init
            git submodule update
            . ~/.nvm/nvm.sh  # Load nvm for the current session
            nvm install 16     # Install Node.js version 16
            nvm use 16
            docker compose down
            docker compose build
            docker compose up -d